### ISSUE TITLE
Items show their required level when holding ctrl

### ISSUE THREAD

**Issue by Rafii2198** [bob10234/WynnWeaponViewer#1]
Wynn Weapon Bigger: 0.5.2
Fabric 0.16.5 for 1.21

When holding ctrl, Wynntils will display required combat level to use equipment on the item, that lvl will be displayed on the bigger weapons too
![image](https://github.com/user-attachments/assets/87da38d1-7867-4b8f-8816-f3187c0fce49)
I am not sure if it is a bug but doesn't look intended

**Comment by DrBiznes** [comment]
That is the intended behavior, I eventually want to add the rarity borders from wynntils behind the zoomed weapon too. When I do that I'll look into adding a config option to disable all other tooltip features than the item itself in the zoomed view.
