### ISSUE TITLE
Shows sold item icon in the trade market

### ISSUE THREAD

**Issue by Rafii2198** [bob10234/WynnWeaponViewer#2]
Wynn Weapon Bigger: 0.5.2
Fabric 0.16.5 for 1.21

When you check your sales and if a sale was a weapon then the bigger item will be a checkmark which I think looks a bit weird and unintended
![image](https://github.com/user-attachments/assets/4a56efd4-ff3f-4286-ba87-9869203f9497)
Probably happens when you didn't sale an item with the red X texture

**Comment by DrBiznes** [comment]
This is because Wynntils still detects the check mark as a weapon, I'll check in the Wynntils discord if they might want to change the behavior in their mod, if not I'll figure out how to hide the checkmark in my mod.

**Comment by DrBiznes** [comment]
Fixed in the latest release.
